DROP FUNCTION IF EXISTS sp_delete_user(UUID, TEXT);
DROP FUNCTION IF EXISTS sp_update_user(UUID, TEXT, TEXT, TEXT, DATE, TEXT, TEXT, INT, TEXT);
DROP FUNCTION IF EXISTS sp_create_user(TEXT, TEXT, TEXT, DATE, TEXT, TEXT, INT, TEXT);
DROP FUNCTION IF EXISTS sp_find_user_by_email(TEXT, UUID);
DROP FUNCTION IF EXISTS sp_get_user(UUID);
DROP FUNCTION IF EXISTS sp_list_users();
